import React from 'react'
import ReactDOM from 'react-dom/client'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'
import './index.css'
import { registerSW } from 'virtual:pwa-register'

// Register service worker for PWA (auto-generated by vite-plugin-pwa)
registerSW({
  onNeedRefresh() {
    // Auto-update when new version available
  },
  onOfflineReady() {
    console.log('App ready to work offline')
  },
})

const router = createRouter({ routeTree })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>,
)
